### ISSUE TITLE
Install tox-ansible from pypi, not github

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-content-actions#8]
This should provide a more stable release for users.

https://github.com/ansible/ansible-content-actions/blob/1c9079c045a1dd8d399a1ae0f3c13b68578478ab/.github/workflows/unit.yaml#L31C1-L32C1

**Comment by minitriga** [comment]
Just hit an issue with this

**Comment by minitriga** [comment]
I have added a PR that will fix the issue.
